-- 코드를 작성해주세요
# SELECT
#     ID
#     , EMAIL
#     , FIRST_NAME
#     , LAST_NAME
# FROM 
#     DEVELOPERS
# WHERE 
#     SUBSTRING(CONV(SKILL_CODE,10,2),-9,1) LIKE 1
#     OR SUBSTRING(CONV(SKILL_CODE,10,2),-11,1) LIKE 1
# ORDER BY
#     ID

SELECT
    ID
    , EMAIL
    , FIRST_NAME
    , LAST_NAME
FROM 
    DEVELOPERS
WHERE
    SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME LIKE 'Python')
    OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME LIKE 'C#')
ORDER BY
    ID
;